language: node_js
node_js: stable
install:
  - yarn
script:
  - bash ./ci/gh-pages.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
  - DEPLOY_DIR: "./sites/example/public"
branches:
  only:
  - master
