language: node_js
node_js: 10
install:
  - yarn install --frozen-lockfile
script:
  - bash ./ci/gh-pages.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
  - DEPLOY_DIR: "./sites/example/public"
branches:
  only:
  - master
